### ISSUE TITLE
failed run exporter inside docker

### ISSUE THREAD

**Issue by Electronn** [justwatchcom/elasticsearch_exporter#59]
Hello,

I try to ran image inside docker build : 
- Dockerfile
```
FROM golang
RUN go get -u github.com/justwatchcom/elasticsearch_exporter
COPY start.sh /
RUN chmod +x /start.sh
CMD /start.sh
```
- start.sh
```
#!/bin/bash
elasticsearch_exporter -es.uri http://my.ip.ad.dr:9200
```
- docker-compose.yml
```
prom-elastic:
  build: ./prom-elastic
  container_name: prom-elastic
  hostname: prom-elastic
  ports:
   - 9108:9108
```
- docker version
```
# docker --version
Docker version 17.03.1-ce, build c6d412e
```

Error : 
```
2017/06/12 20:45:58 Starting Server: :9108
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f8062]

goroutine 49 [running]:
github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(0x0, 0xc42009c938, 0x2, 0x2, 0xa77300, 0xc42027b200)
        /go/src/github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus/counter.go:139 +0x22
main.(*Exporter).Collect(0xc420194080, 0xc420196480)
        /go/src/github.com/justwatchcom/elasticsearch_exporter/exporter.go:459 +0x39af
github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).writePB.func2(0xc4201b4750, 0xc420196480, 0xa252e0, 0xc420194080)
        /go/src/github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:420 +0x61
created by github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus.(*registry).writePB
        /go/src/github.com/justwatchcom/elasticsearch_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:421 +0x274
```

**Comment by Foxsa** [comment]
+1

**Comment by dominikschulz** [comment]
Which ES versions are you using? Couldn't reproduce with ES 5.4.1.

**Comment by Foxsa** [comment]
tested on 5.4.0 and 2.4.1

**Comment by Electronn** [comment]
2.4.5 , 5.4.1

**Comment by dominikschulz** [comment]
Hmm, will need some more time to investigate ...

**Comment by Electronn** [comment]
Also tested on 4 different servers ( exporters ) with various hardware.

**Comment by dominikschulz** [comment]
Can you please check if the issue is gone with 0.3.3? Works for us (but 0.3.1 also did ...)

**Comment by Foxsa** [comment]
It works for me now! Thanks!

**Comment by dominikschulz** [comment]
In case you have any trouble with the current 1.0.0-rc1 or later, please open another issue.
